import tinytuya
from tinytuya.Contrib import RFRemoteControlDevice

buttons={
"play-pause": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJtaGRTQkljQlVnU0hBWWNCVWdSTkFWSUVod0ZTQkljQlVnUk5BVklFaHdGU0JJY0JVZ1JTQkljQlVnU0hBWWNCVWdSU0JJY0JVZ1NIQVljQlVnUlNCSWNCaHdGU0JGSUVod0dIQVZJRVVnU0hBVklFaHdGU0JJY0Jod0ZTQkljQlVnUlNCSWNCaHdGU0JJY0JVZ1NIQVZJRVVnUk5BVklFIiwibHYiOlswXX0=",
"1": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJYaHBTQkljQlVnU0hBWWNCVWdTSEFWSUVod0ZTQkljQlVnU0hBVklFaHdGU0JJY0JVZ1JTQkV3QlVnU0hBWWNCVWdSU0JJY0JVZ1NIQVljQlVnUlNCSWNCaHdGU0JGSUVUQUdIQVZJRVVnU0hBVklFaHdGU0JJY0JVZ1NIQVZJRWh3R0hBVklFVWdTSEFZY0JVZ1NIQVZJRWh3RlNCSWNCIiwibHYiOlswXX0=",
"2": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJmUmRGQklNQlJRUlZBWU1CUlFTREFVVUVnd0ZvQkZVQmFBU0RBVVVFZ3dGRkJJTUJhQVJGQklNQlJRU0RBWU1CUlFSRkJJTUJSUVNEQVlNQmFBUkZCSU1CZ3dGb0JFVUVnd0dEQVVVRWFBU0RBVVVFZ3dGRkJJTUJSUVNEQVlNQlJRU0RBV2dFUlFTREFZTUJSUVNEQVVVRWd3RkZCRVVFIiwibHYiOlswXX0=",
"3": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJreHBSQkhzQlVRUjdBWHNCVVFSN0FWRUVld0ZSQkhzQlVRUjdBVkVFZXdGUkJIc0JVUVJSQkhzQlVRUjdBWHNCVVFSUkJIc0JVUVI3QVhzQlVRUlJCSHNCZXdGUkJGRUVld0Y3QVZFRVVRUjdBVkVFZXdGUkJIc0Jld0ZSQkZFRWV3RjdBVkVFVVFSN0FYc0JVUVI3QVZFRVVRUjdBWHNCIiwibHYiOlswXX0=",
"4": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJkUmRSQkhzQlVRUjdBWHNCVVFSN0FWRUVld0ZSQkhzQlVRUjdBVkVFZXdGUkJIc0JVUVJSQkhzQlVRUjdBWHNCVVFSUkJIc0JVUVI3QVhzQlVRUlJCSHNCZXdGUkJGRUVld0Y3QVZFRVVRUjdBVkVFZXdGUkJIc0Jld0ZSQkhzQlVRUjdBVkVFVVFSN0FYc0JVUVI3QVZFRVVRUjdBVkVFIiwibHYiOlswXX0=",
"5": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJvQnBSQkhzQlVRUjdBWHNCVVFSN0FWRUVld0ZSQkhzQlVRUjdBVkVFZXdGUkJIc0JVUVJSQkhzQlVRUjdBWHNCVVFSUkJIc0JVUVI3QVhzQlVRUlJCSHNCZXdGUkJGRUVld0Y3QVZFRVVRUjdBVkVFZXdGN0FWRUVVUVI3QVZFRWV3RjdBVkVFVVFSN0FYc0JVUVJSQkhzQmV3RlJCSHNCIiwibHYiOlswXX0=",
"6": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJMUmRRQkhzQlVBUjdBWHNCVUFSN0FWQUVld0ZRQkhzQlVBUjdBVkFFZXdGUUJIc0JVQVJRQkhzQlVBUjdBWHNCVUFSUUJIc0JVQVI3QVhzQlVBUlFCSHNCZXdGUUJGQUVld0Y3QVZBRVVBUjdBVkFFZXdGN0FWQUVVQVI3QVhzQlVBUjdBVkFFVUFSN0FYc0JVQVJRQkhzQmV3RlFCRkFFIiwibHYiOlswXX0=",
"random": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJuaGRQQkh3QlR3UjhBWHdCVHdSOEFVOEVmQUZQQkh3QlR3UjhBVThFZkFGUEJId0JUd1JQQkh3QlR3UjhBWHdCVHdSUEJId0JUd1I4QVh3QlR3UlBCSHdCZkFGUEJFOEVmQUY4QVU4RVR3UjhBVThFZkFGOEFVOEVmQUZQQkh3QlR3UjhBVThFVHdSOEFYd0JUd1JQQkh3QlR3UjhBVThFIiwibHYiOlswXX0=",
"invert": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJTQnBSQkUwQlVRU0VBWVFCVVFTRUFWRUVoQUZSQklRQlVRU0VBVkVFaEFGUkJJUUJVUVJSQklRQlVRU0VBWVFCVVFSUkJJUUJVUVNFQVlRQlVRUlJCSVFCaEFGUkJGRUVoQUdFQVZFRVVRU0VBVkVFaEFHRUFWRUVoQUZSQkZFRVRRR0VBVkVFVVFTRUFZUUJVUVJSQklRQlVRU0VBVTBCIiwibHYiOlswXX0=",
"1h": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJ0QmRTQklZQlVnU0dBWVlCVWdTR0FWSUVoZ0ZTQklZQlVnU0dBVklFaGdGU0JJWUJVZ1JTQklZQlVnUk1BWVlCVWdSU0JFd0JVZ1NHQVlZQlVnUlNCSVlCaGdGU0JGSUVUQUdHQVZJRVVnU0dBVXdCVWdSU0JJWUJoZ0ZTQklZQlVnUlNCSVlCaGdGU0JGSUVUQUdHQVZJRVVnU0dBVklFIiwibHYiOlswXX0=",
"2h": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJLaHBVQklnQlZBU0lBWWdCVkFTSUFWUUVpQUZVQklnQlZBUkxBVlFFaUFGVUJJZ0JWQVJVQklnQlZBUkxBWWdCVkFSVUJJZ0JWQVNJQVlnQlZBUlVCSWdCaUFGVUJGUUVpQUdJQVZRRVZBU0lBWWdCVkFTSUFWUUVpQUZVQkZRRWlBRlVCSWdCaUFGVUJGUUVpQUZVQklnQlZBU0lBVXNCIiwibHYiOlswXX0=",
"4h": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJPUnBQQkh3QlR3UjhBWHdCVHdSOEFVOEVmQUZQQkh3QlR3UjhBVThFZkFGUEJId0JUd1JQQkh3QlR3UjhBWHdCVHdSUEJId0JUd1I4QVh3QlR3UlBCSHdCZkFGUEJFOEVmQUY4QVU4RVR3UjhBWHdCVHdSOEFVOEVUd1I4QVU4RWZBRlBCSHdCZkFGUEJFOEVmQUZQQkh3QmZBRlBCSHdCIiwibHYiOlswXX0=",
"8h": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJtUmRRQkhzQlVBUjdBWHNCVUFSN0FWQUVld0ZRQkhzQlVBUjdBVkFFZXdGUUJIc0JVQVJRQkhzQlVBUjdBWHNCVUFSUUJIc0JVQVI3QVhzQlVBUlFCSHNCZXdGUUJGQUVld0Y3QVZBRVVBUjdBVkFFZXdGN0FWQUVVQVI3QVhzQlVBUlFCSHNCZXdGUUJIc0JVQVJRQkhzQmV3RlFCRkFFIiwibHYiOlswXX0=",
"luz": "eyJudW0iOjEsImZlcSI6MCwiZGF0YTAiOiJaQnBSQkhzQlVRUjdBWHNCVVFSN0FWRUVld0ZSQkhzQlVRUjdBVkVFZXdGUkJIc0JVUVJSQkhzQlVRUjdBWHNCVVFSUkJIc0JVUVI3QVhzQlVRUlJCSHNCZXdGUkJGRUVld0Y3QVZFRVVRUjdBWHNCVVFSUkJIc0Jld0ZSQkZFRWV3RlJCSHNCZXdGUkJGRUVld0Y3QVZFRVVRUjdBWHNCIiwibHYiOlswXX0=",
}


rf=RFRemoteControlDevice.RFRemoteControlDevice
def generate_codes():
    """Print ESPHome raw-transmit YAML for the captured button codes."""
    print("button:")
    w = 10
    for b in buttons:
        decoded = rf.rf_decode_button(buttons[b])
        pulses = rf.base64_to_pulses(decoded["data0"])
        print("  - platform: template")
        print("    name: ", b)
        print("    web_server_sorting_weight: ", w)
        w += 10
        print("    on_press:")
        print("       - output.turn_on: status")
        print("       - remote_transmitter.transmit_raw:")
        print("          transmitter_id: rf")
        print("          repeat:")
        print("            times: 7")
        print("            wait_time: 0s")
        pp = []
        mult = 1
        for pulse in pulses:
            pp.append(str(pulse * mult))
            mult = -mult
        print("          code: [" + ",".join(pp) + "]")
        print("       - output.turn_off: status")

if __name__ == "__main__":
    generate_codes()
